{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-license"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  license: {{ .Values.license | quote }}
{{- end }}
