apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-uninstall
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: redis-enterprise-operator
      restartPolicy: Never
      containers:
        - name: redis-cluster-uninstall
          image: rancher/kubectl:v1.33.5
          command:
            - |
              kubectl patch rec {{ .Values.name }} -p '{"metadata":{"finalizers":null}}' --type=merge -n {{ .Release.Namespace }}
