{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cs.fullname" . }}-config
  labels:
    {{- include "cs.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: {{ include "cs.fullname" . }}-config
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "cs.labels" . | nindent 10 }}
      data:
        REDIS_PASSWORD: "{{ `{{` }} .password {{ `}}` }}"
        SECRET_ENCRYPTION_KEY: "{{ `{{` }} .key {{ `}}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.password.key }}
        {{- if .Values.externalSecret.password.property }}
        property: {{ .Values.externalSecret.password.property }}
        {{- end }}
    - secretKey: key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.encryption.key }}
        {{- if .Values.externalSecret.encryption.property }}
        property: {{ .Values.externalSecret.encryption.property }}
        {{- end }}
{{- end }}
