{{- if and (not .Values.license.existingSecret) .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cs.fullname" . }}-license
  labels:
    {{- include "cs.labels" . | nindent 4 }}
type: Opaque
data:
  LICENSE_KEY: {{ .Values.license.key | b64enc | quote }}
{{- end }}
