apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.localName }}-reaadb-secret"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: "{{ .Values.localName }}-reaadb-secret"
    creationPolicy: Owner
    template:
      data:
        username: {{ .Values.username }}
        password: "{{ `{{` }} .password {{ `}}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.clusterKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.remoteName }}-reaadb-secret"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: "{{ .Values.remoteName }}-reaadb-secret"
    creationPolicy: Owner
    template:
      data:
        username: {{ .Values.username }}
        password: "{{ `{{` }} .password {{ `}}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.clusterKey }}
