apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "redis-enterprise-{{ .Values.localName }}"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: "redis-enterprise-{{ .Values.localName }}"
    creationPolicy: Owner
    template:
      data:
        username: {{ .Values.username }}
        password: "{{ `{{` }} .password {{ `}}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.clusterKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "redis-enterprise-{{ .Values.remoteName }}"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.store.kind }}
    name: {{ .Values.externalSecret.store.name }}
  target:
    name: "redis-enterprise-{{ .Values.remoteName }}"
    creationPolicy: Owner
    template:
      data:
        username: {{ .Values.username }}
        password: "{{ `{{` }} .password {{ `}}` }}"
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.externalSecret.clusterKey }}
