{{- if .Values.ingress.enabled }}
{{- range .Values.databases }}
apiVersion: ingress.v1.haproxy.org/v1
kind: TCP
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    ingress.class: haproxy
spec:
  - name: {{ .name }}
    frontend:
      name: "redis-{{ .port }}"
      binds:
        - name: "redis-{{ .port }}"
          port: {{ .port }}
    service:
      name: {{ .name }}
      port: {{ .port }}
---
{{- end }}
{{- end }}
