{{- range .Values.databases }}
{{- $databaseName := .name }}
{{- $existingDatabase := (lookup "app.redislabs.com/v1alpha1" "RedisEnterpriseActiveActiveDatabase" $.Release.Namespace $databaseName) }}
{{- if not $existingDatabase }}
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseActiveActiveDatabase
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  participatingClusters:
    - name: {{ $.Values.localName }}
    - name: {{ $.Values.remoteName }}
  globalConfigurations:
    shardCount: {{ .shards | default $.Values.defaults.shards }}
    databasePort: {{ .port }}
    memorySize: {{ .memory | default $.Values.defaults.memory }}
    persistence: {{ .persistence | default $.Values.defaults.persistence }}
    proxyPolicy: {{ .proxyPolicy | default $.Values.defaults.proxyPolicy }}
    evictionPolicy: {{ .eviction | default $.Values.defaults.eviction }}
    replication: {{ .replication | default $.Values.defaults.replication }}
    shardsPlacement: {{ .placement | default $.Values.defaults.placement }}
    databaseSecretName: "{{ .name }}-secret"
    {{- $tlsMode := "replica_ssl" }}
    {{- if or .tls (and (not (hasKey . "tls")) $.Values.defaults.tls) }}
    {{- $tlsMode = "enabled" }}
    {{- end }}
    tlsMode: {{ $tlsMode }}
---
{{- end }}
{{- end }}
