apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRemoteCluster
metadata:
  name: {{ .Values.localName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  recName: {{ .Values.localClusterName }}
  recNamespace: {{ .Values.localNamespace }}
  apiFqdnUrl: "api-{{ .Values.localClusterName }}.{{ .Values.dns.localDomain }}"
  dbFqdnSuffix: "-db-{{ .Values.localClusterName }}.{{ .Values.dns.localDomain }}"
  secretName: "redis-enterprise-{{ .Values.localName }}"
---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseRemoteCluster
metadata:
  name: {{ .Values.remoteName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  recName: {{ .Values.remoteClusterName }}
  recNamespace: {{ .Values.remoteNamespace }}
  apiFqdnUrl: "api-{{ .Values.remoteClusterName }}.{{ .Values.dns.remoteDomain }}"
  dbFqdnSuffix: "-db-{{ .Values.remoteClusterName }}.{{ .Values.dns.remoteDomain }}"
  secretName: "redis-enterprise-{{ .Values.remoteName }}"
