{{- if .Values.clusterCaCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchbase-cng.clusterCaSecretName" . }}
  namespace: {{ include "couchbase-cng.namespace" . }}
  labels:
    {{- include "couchbase-cng.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-ca.crt: |
    {{- .Values.clusterCaCert | nindent 4 }}
{{- end }}
