{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchbase-cng.secretName" . }}
  namespace: {{ include "couchbase-cng.namespace" . }}
  labels:
    {{- include "couchbase-cng.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
{{- end }}
