{{- if and .Values.ingress.enabled .Values.dns.domain }}
{{- if eq .Values.ingress.type "haproxy" }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-insight-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $ht := htpasswd .Values.ingress.username .Values.ingress.password }}
  {{- $parts := splitList ":" $ht }}
  {{ .Values.ingress.username }}: {{ index $parts 1 | quote }}
{{- end }}
{{- end }}
