{{- if and .Values.ingress.enabled .Values.dns.domain }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-insight-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ printf "%s::%s" .Values.ingress.username .Values.ingress.password | b64enc }}
{{- end }}
