{{- if and .Values.ingress.enabled .Values.dns.domain }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-insight-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: |
    {{ htpasswd .Values.ingress.username .Values.ingress.password }}
{{- end }}
