{{- if and .Values.tls.enabled .Values.dns.domain -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis-insight
type: kubernetes.io/tls
data:
  {{- $domain := .Values.dns.domain }}
  {{- $name := printf "redis-insight.%s" $domain }}
  {{- $host := list $name }}
  {{- $cert := genSelfSignedCert "redis-insight" nil $host 365 }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end -}}
