apiVersion: v2
name: active-active
description: A Helm chart for configuring an active-active Redis deployment
type: application
version: 0.3.2
appVersion: "8.0.10"
keywords:
  - redis
  - database
maintainers:
  - name: Michael Minichino
