#

defaults:
  memory: 1GB
  replication: true
  shards: 1
  placement: sparse
  eviction: noeviction
  persistence: aofEverySecond
  proxyPolicy: all-master-shards
  ossCluster: false
  tls: false

databases:
  - name: reaadb
    memory: 1GB
    replication: true
    shards: 1
    placement: sparse
    port: 12012
    eviction: noeviction
    persistence: aofEverySecond
    proxyPolicy: all-master-shards
    ossCluster: false
    tls: false

username: "admin@redis.com"

localName: east
remoteName: west

localClusterName: cluster-east
remoteClusterName: cluster-west

localNamespace: redis
remoteNamespace: redis

dns:
  localDomain: cluster.local
  remoteDomain: cluster.remote

externalSecret:
  enabled: true
  store:
    kind: ClusterSecretStore
    name: secret-store
  clusterKey: cluster-key
  databaseKey: reaadb-key

ingress:
  enabled: false
