apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount }}
            namespace: {{ .Release.Namespace }}
